### ISSUE TITLE
attacking fish man leads to AssertionError

### ISSUE THREAD

**Issue by xmunoz** [Cronenbrogues/cronenbroguelike#22]
Might be related to #19, since this exception was raised after I committed suicide.
```
> attack fish man
🎵 MMMMMMMMBOP ba duba dop ba du dop DING DONG 🎵
You miss.
Traceback (most recent call last):
  File "demo.py", line 104, in <module>
    adventurelib.start()
  File "/home/user/workspace/cronenbroguelike/venv/lib/python3.8/site-packages/adventurelib.py", line 536, in start
    _handle_command(cmd)
  File "/home/user/workspace/cronenbroguelike/venv/lib/python3.8/site-packages/adventurelib.py", line 509, in _handle_command
    func(**args)
  File "<string>", line 4, in wrapped
  File "/home/user/workspace/cronenbroguelike/cronenbroguelike/commands.py", line 236, in attack
    assert character.ai is not None
AssertionError
```

**Comment by xmunoz** [comment]
Just tried again from a fresh load, and same error. Maybe not related to #19.
